### ISSUE TITLE
Samsung Notebook 9 Pen not detected

### ISSUE THREAD

**Issue by retrop7** [linuxwacom/libwacom#139]
I've got this laptop and am trying to get the pen recognized.  
https://www.samsung.com/us/computing/windows-laptops/notebook-series-9/notebook-9-pen-13-3--np930qaa-k01us/

I cannot figure out how to get the correct data file
```
[retrop@retrop-laptop ~]$ libinput record
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	Intel Virtual Button driver
/dev/input/event5:	PC Speaker
/dev/input/event6:	SYN2602:00 06CB:78C9 Touchpad
/dev/input/event7:	Atmel Atmel maXTouch Digitizer
/dev/input/event8:	WCOM0032:00 2D1F:002E Mouse
/dev/input/event9:	WCOM0032:00 2D1F:002E
/dev/input/event10:	Atmel Atmel maXTouch Digitizer Pen
/dev/input/event11:	720p HD Camera: 720p HD Camera
/dev/input/event12:	720p HD Camera: Samsung IR Came
/dev/input/event13:	Video Bus
/dev/input/event14:	HDA Intel PCH Mic
/dev/input/event15:	HDA Intel PCH Headphone
/dev/input/event16:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event17:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event18:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event19:	HDA Intel PCH HDMI/DP,pcm=9
/dev/input/event20:	HDA Intel PCH HDMI/DP,pcm=10
Select the device event number: 9
Recording to 'stdout'.
version: 1
ndevices: 1
libinput:
  version: "1.13.4"
  git: "unknown"
system:
  kernel: "4.19.62-1-MANJARO"
  dmi: "dmi:bvnAmericanMegatrendsInc.:bvrP05AGN.028.181029.MK:bd10/29/2018:svnSAMSUNGELECTRONICSCO.,LTD.:pn930QAA:pvrP05AGN:rvnSAMSUNGELECTRONICSCO.,LTD.:rnNP930QAA-K01US:rvrSGL9117A0W-C01-G001-S0001+10.0.16299:cvnSAMSUNGELECTRONICSCO.,LTD.:ct31:cvrN/A:"
devices:
- node: /dev/input/event9
  evdev:
    # Name: WCOM0032:00 2D1F:002E
    # ID: bus 0x18 vendor 0x2d1f product 0x2e version 0x100
    # Size in mm: 293x165
    # Supported Events:
    # Event type 0 (EV_SYN)
    # Event type 1 (EV_KEY)
    #   Event code 320 (BTN_TOOL_PEN)
    #   Event code 321 (BTN_TOOL_RUBBER)
    #   Event code 330 (BTN_TOUCH)
    #   Event code 331 (BTN_STYLUS)
    #   Event code 332 (BTN_STYLUS2)
    # Event type 3 (EV_ABS)
    #   Event code 0 (ABS_X)
    #       Value        1901
    #       Min             0
    #       Max         29376
    #       Fuzz            0
    #       Flat            0
    #       Resolution    100
    #   Event code 1 (ABS_Y)
    #       Value        4478
    #       Min             0
    #       Max         16524
    #       Fuzz            0
    #       Flat            0
    #       Resolution    100
    #   Event code 24 (ABS_PRESSURE)
    #       Value           0
    #       Min             0
    #       Max          4095
    #       Fuzz            0
    #       Flat            0
    #       Resolution      0
    #   Event code 26 (ABS_TILT_X)
    #       Value           0
    #       Min         -9000
    #       Max          9000
    #       Fuzz            0
    #       Flat            0
    #       Resolution   5730
    #   Event code 27 (ABS_TILT_Y)
    #       Value           0
    #       Min         -9000
    #       Max          9000
    #       Fuzz            0
    #       Flat            0
    #       Resolution   5730
    # Event type 4 (EV_MSC)
    #   Event code 4 (MSC_SCAN)
    # Properties:
    name: "WCOM0032:00 2D1F:002E"
    id: [24, 11551, 46, 256]
    codes:
      0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # EV_SYN
      1: [320, 321, 330, 331, 332] # EV_KEY
      3: [0, 1, 24, 26, 27] # EV_ABS
      4: [4] # EV_MSC
    absinfo:
      0: [0, 29376, 0, 0, 100]
      1: [0, 16524, 0, 0, 100]
      24: [0, 4095, 0, 0, 0]
      26: [-9000, 9000, 0, 0, 5730]
      27: [-9000, 9000, 0, 0, 5730]
    properties: []
  hid: [5, 1, 9, 2, 161, 1, 133, 1, 9, 1, 161, 0, 5, 9, 25, 1, 41, 2, 21, 0, 37, 1, 149, 2, 117, 1, 129, 2, 149, 1, 117, 6, 129, 3, 5, 1, 9, 48, 9, 49, 21, 129, 37, 127, 117, 8, 149, 2, 129, 6, 192, 192, 5, 13, 9, 2, 161, 1, 133, 2, 9, 32, 161, 0, 9, 66, 9, 68, 9, 69, 9, 60, 9, 90, 9, 50, 21, 0, 37, 1, 117, 1, 149, 6, 129, 2, 149, 2, 129, 3, 5, 1, 9, 48, 38, 192, 114, 70, 192, 114, 101, 17, 85, 13, 117, 16, 149, 1, 129, 2, 9, 49, 38, 140, 64, 70, 140, 64, 129, 2, 69, 0, 101, 0, 85, 0, 5, 13, 9, 48, 38, 255, 15, 129, 2, 6, 0, 255, 9, 4, 117, 8, 38, 255, 0, 70, 255, 0, 101, 17, 85, 14, 129, 2, 5, 13, 9, 61, 117, 16, 22, 216, 220, 38, 40, 35, 54, 216, 220, 70, 40, 35, 101, 20, 129, 2, 9, 62, 129, 2, 101, 0, 85, 0, 21, 0, 53, 0, 69, 0, 192, 9, 0, 117, 8, 38, 255, 0, 177, 18, 133, 3, 9, 0, 149, 18, 177, 18, 133, 4, 9, 0, 177, 2, 133, 5, 9, 0, 149, 4, 177, 2, 133, 6, 9, 0, 149, 36, 177, 2, 133, 21, 9, 0, 149, 1, 177, 2, 133, 22, 9, 0, 21, 0, 38, 255, 0, 149, 6, 177, 2, 133, 23, 9, 0, 149, 12, 177, 2, 192, 6, 0, 255, 9, 0, 161, 1, 133, 9, 5, 13, 9, 32, 161, 0, 9, 0, 38, 255, 0, 117, 8, 149, 12, 129, 2, 192, 9, 0, 149, 3, 177, 18, 192, 6, 0, 255, 9, 2, 161, 1, 133, 7, 9, 0, 149, 73, 177, 2, 133, 8, 9, 0, 149, 3, 129, 2, 9, 0, 177, 2, 192 ]
  udev:
    properties:
    - ID_INPUT=1
    - ID_INPUT_HEIGHT_MM=165
    - ID_INPUT_TABLET=1
    - ID_INPUT_WIDTH_MM=293
    - LIBINPUT_DEVICE_GROUP=18/2d1f/2e:i2c-WCOM0032:00
  quirks:
  events:

```
