### ISSUE TITLE
Add support for the dual-tablet on the Lenovo Yoga Book 9i

### ISSUE THREAD

**Issue by whot** [linuxwacom/libwacom#602]
See [gnome-control-center#2727](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2727), the Lenovo Yoga Book 9i has two built-in identical tablets currently listed as

```
- name: 'INGENIC Gadget Serial and keyboard Stylus'
  bus: 'usb'
  vid: '0x17ef'
  pid: '0x6161'
  nodes: 
  - /dev/input/event10: 'INGENIC Gadget Serial and keyboard Touchpad'
  - /dev/input/event9: 'INGENIC Gadget Serial and keyboard Stylus'
  - /dev/input/event8: 'INGENIC Gadget Serial and keyboard Stylus'
  - /dev/input/event7: 'INGENIC Gadget Serial and keyboard'
```

We may need some extra information to tell libwacom consumers that this is a dual-tablet device, though right now I'm not sure how that information would look like or how it'd be used.
