### ISSUE TITLE
Add Lenovo Precision Pen 2

### ISSUE THREAD

**Issue by RayJW** [linuxwacom/libwacom#774]
Something changed in GNOME 47 and the non-eraser button on my stylus has become basically useless as it now simply acts as a left-click instead of correctly mapping to secondary actions in apps like Xournal++ or Rnote. I saw [this,](https://who-t.blogspot.com/2024/06/gnome-tablet-support-papercut-fixes.html) and I think one of the defaults that changed may have affected that behaviour.

I know that this is only vaguely related to libwacom, so this is just background info. Now the real question. I saw that there is now support for non-wacom styli. How can I help to get my stylus supported, so I can properly adjust the button mappings. At the moment, `sudo libwacom-show-stylus` simply prints the serial number and `Unknown stylus id 0x866b. New entry needed`.

I searched the wiki and all the other repos, but there doesn't seem to be any info about this for the time being, and the error only reads `Suggested line for .tablet file: Styli=` which doesn't help.

- **Device name**: Lenovo Precision Pen 2 (2023)
- **Device model identifier**: ZG38C04471 ?
- **libwacom version**: 2.13.0-1

- [X] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

**Comment by whot** [comment]
if the button mapping doesn't work, please file a bug with gnome-control-center, thanks. this is not something libwacom can control.

All the styli are in `libwacom.stylus` though now that we have multiple vendors we should probably split them by vendor (i.e. `wacom.stylus` etc.). In your case adding `lenovo.stylus` and filling it with the same bits as the existing styli should work, we do read all `.stylus` files.

**Comment by RayJW** [comment]
> if the button mapping doesn't work, please file a bug with gnome-control-center, thanks. this is not something libwacom can control.

Hmm, okay, I'm sorry then. I stumbled upon [this issue](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2279) when looking at gnome-control-center which is why I ended up back here since I thought this was the same underlying problem. Thank you for your patience ^^

> All the styli are in `libwacom.stylus` though now that we have multiple vendors we should probably split them by vendor (i.e. `wacom.stylus` etc.). In your case adding `lenovo.stylus` and filling it with the same bits as the existing styli should work, we do read all `.stylus` files.

Should I keep this issue open and close it once this is changed? I'll gladly help with getting this done! Would you like me to try to open a PR for that, or is it too “early” in the restructuring?

**Comment by whot** [comment]
so basically: libwacom says "stylus has N buttons" and then GNOME (or $other) is responsible for actually mapping those buttons to something. It's libwacom's bug when the information is wrong but here it sounds like it's the actual mapping that doesn't work?

What does `libwacom-list-local-devices` say for example? Most tablets should default to the generic pen anyway and arguably even adding your stylus isn't truly necessary for it to work.

Having said that, I've merged #780 now, if you can send a PR for `lenovo.stylus` that'd be great!

**Comment by RayJW** [comment]
> What does `libwacom-list-local-devices` say for example? Most tablets should default to the generic pen anyway and arguably even adding your stylus isn't truly necessary for it to work.

```
devices:
- name: 'Wacom HID 52C2'
  bus: 'i2c'
  vid: '0x056a'
  pid: '0x52c2'
  nodes: 
  - /dev/input/event11: 'Wacom HID 52C2 Pen'
  styli:
   - id: 0x1
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x11
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x19
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x21
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x31
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x39
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x49
     name: 'Bamboo Ink'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x71
     name: 'Bamboo Ink'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x221
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x231
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x271
     name: 'Bamboo Ink'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x421
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x431
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x621
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x631
     name: 'Dell Active Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x8051
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 0
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x805b
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x806b
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x807b
     name: 'Bamboo Ink Plus'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x826b
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
   - id: 0x846b
     name: 'AES Pen'
     type: 'mobile'
     axes: ['x', 'y' , 'tilt', 'pressure']
     buttons: 1
     is_eraser: 'true'
     eraser_type: 'button'
```

This is the output for `sudo libwacom-list-local-devices` but only because I have the tablet file that I submitted a PR for in /etc/libwacom until a new version is released.

And for `sudo libwacom-show-stylus` the output looks like this:

```
Using "Wacom HID 52C2 Pen": /dev/input/event11
Using stylus file(s): /usr/share/libwacom/libwacom.stylus
Tool id 0x866b serial 0x80208cd7 in-proximity: False 
^CTerminating
Unknown stylus id 0x866b. New entry needed
Suggested line for .tablet file:
Styli=
```
