### ISSUE TITLE
Huion RTP-700 wrong device match and aspect ratio after firmware update

### ISSUE THREAD

**Issue by maruseu** [linuxwacom/libwacom#784]
- **Device name**: Huion RTP-700
- **Device model identifier**: RTP-700
- **libwacom version**: 2.13.0-1

- [x] I understand that libwacom does affect whether the device works (see [Troubleshooting](https://github.com/linuxwacom/libwacom/wiki/Troubleshooting#my-tablet-doesnt-work))

# Bug description

The graphics tablet doesn't show up in GNOME Settings after an update to its firmware. 
The names that show up in evtest are
```
HUION Huion Tablet_RTP_700 Pen
HUION Huion Tablet_RTP_700
```
In lsusb:
```
Bus 005 Device 004: ID 256c:0064 HUION Huion Tablet_RTP_700
```
I dont know how to edit the .tablet's DeviceMatch to properly support it but I just removed the name from the match and that made it show up in the settings program however when i use the "keep aspect ratio" option it is corrected to a wrong aspect ratio. The tablet is physically 23:14 and when using "keep aspect ratio" on a 16:9 monitor the active area becomes 23:8 (or 16:5.6).

**Comment by whot** [comment]
Hooray. The update probably changed the firmware version that we need to identify the tablet since Huion thinks it's fun to have multiple devices use the same USB product ids.

Can you run https://github.com/whot/huion-switcher please and let us know what the output of that is? Thanks.

**Comment by maruseu** [comment]
Thank you for your work. It outputs:

```
HUION_FIRMWARE_ID="HUION_T19k_220310"
HUION_MAGIC_BYTES="130348da00688800ff1fd81303060001043c3e"
```

**Comment by whot** [comment]
weird, that seems to be the same firmware id as before, see the `data/huion-rtp-700.tablet` file[^1]. What does `libwacom-list-local-devices` say?


[^1]: concidentally, that one hasn't been reviewed by anyone with the device, it'd be great if you could update it!

**Comment by maruseu** [comment]
In an unmodified system
```
/dev/input/event5 is a tablet but not supported by libwacom
/dev/input/event6 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```
With the aforementioned workaround
```
devices:
- name: 'Huion RTP-700'
  bus: 'usb'
  vid: '0x256c'
  pid: '0x0064'
  nodes: 
  - /dev/input/event11: 'HUION Huion Tablet_RTP_700 Pen'
  - /dev/input/event12: 'HUION Huion Tablet_RTP_700'
  styli:
   - id: 0xffffd
     name: 'General Pen with no Eraser'
     type: 'general'
     axes: ['x', 'y' , 'pressure']
     buttons: 2
     erasers: []
```
Im not sure if it is related but I also noticed the top pen button started acting as flipping the pen instead of a button, this pen has no eraser and libwacom correctly reports as such. Before the firmware update both buttons worked as buttons.

>     1. concidentally, that one hasn't been reviewed by anyone with the device, it'd be great if you could update it! [↩](#user-content-fnref-1-1a60bc734014950f0ecbe24617af631f)

Everything looks correct, except the size is 11x6.9 inches. I sent the sysinfo in [https://github.com/linuxwacom/wacom-hid-descriptors/issues/420](url)
